/* =================================================================================================
   TERMCHAMP PHONE APP — PLANNER DATA AND RULES (app/planner.js)
   -------------------------------------------------------------------------------------------------
   GENERATED by app-dev/source/build.py from the desktop's index.html. Everything between the
   @@LIFTED markers is copied out of index.html character for character — the flowcharts, GE list,
   concentrations, the quarter→semester crosswalk, the legal pages, and the functions that decide
   whether a requirement is filled. The phone and the desktop therefore cannot disagree about a
   student's degree. To change a rule, change it in index.html and rebuild this file.

   Loaded only when the Planner, Settings or Edit profile is opened: it is ~0.5 MB of data the other
   screens never need.
   ================================================================================================= */
(function () {
  /* ---- the student, as the lifted functions expect to find them ---- */
  var student = { major: '', conc: '', standing: '' };
  var myHistory = [];          // class_history rows: {code, term, year, professor}
  var myClasses = [];          // this term's class codes
  var myWaived = {};           // class_waivers: code -> reason
  var myClassMeta = {};
  function completedLocal() { return []; }                 // the desktop's device mirror; the phone reads the account only
  function waivedMap() { var o = {}; Object.keys(myWaived).forEach(function (c) { o[canonCode(c)] = myWaived[c]; }); return o; }
  function waivedCodes() { return Object.keys(waivedMap()); }
  function secsOf() { return null; }                       // enrolledNowCodes(): no section detail = enrolled
  function schConc() { return (student.conc && student.conc !== 'General / Open') ? student.conc : null; }
  var COURSE_NAME = {}, CLASS_INDEX = {};
  function fp_name(c) { return COURSE_NAME[c] || ''; }   // the desktop's catalog-name lookup, for dprParse

  /* @@LIFTED:BEGIN */
  /* @@LIFTED:END */

  /* ---- the ledger: the desktop's plLedgerCompute(), minus its DOM ------------------------------
     Same rules, same order: one completion fills one slot (a repeatable course named three times
     needs three terms on the record); coded slots first, then GE and electives through
     uncodedSatisfied(); anything slotCheckable() can't judge goes on the "can't check" list. */
  function norm(x) { return String(x || '').toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]/g, ''); }
  function majorFor(name) {
    if (!name) return null;
    var key = Object.keys(window.SCHED_MAJORS).find(function (k) { return norm(window.SCHED_MAJORS[k].name) === norm(name); });
    return key ? window.SCHED_MAJORS[key] : null;
  }
  function ledger() {
    var base = majorFor(student.major); if (!base) return null;
    var mm = schExpandConc(base);
    var have = {};
    myHistory.forEach(function (h) { if (h && h.code) { var k = canonCode(h.code); have[k] = (have[k] || 0) + 1; } });
    completedCodes().forEach(function (c) { if (!have[c]) have[c] = 1; });
    var takingM = {}; myClasses.forEach(function (c) { var k = canonCode(c); takingM[k] = (takingM[k] || 0) + 1; });
    var uc = uncodedSatisfied(mm, completedCodes(), myClasses.slice());
    var rows = { major: { label: 'Major courses', f: 0, t: 0, n: 0 }, conc: null, ge: { label: 'General education', f: 0, t: 0, n: 0 }, el: { label: 'Electives', f: 0, t: 0, n: 0 } };
    var cant = [], concUnchosen = 0, concNote = '', concLabel = '', need = [], needU = [], done = [];
    /* The same walk, remembered per slot, is the year-by-year grid: every slot of the flowchart
       with the state this ledger gave it — so the grid and the counts can never disagree. */
    var grid = (mm.terms || []).map(function (t) { return { year: t.year, term: t.term, slots: [] }; });
    (mm.terms || []).forEach(function (t, ti) {
      (t.slots || []).forEach(function (sl) {
        var isConc = (sl.type === 'concentration') || /concentration/i.test(sl.note || '');
        var cell = { id: sl.id, title: sl.title || '', code: sl.code || '', units: sl.units, type: sl.type, note: sl.note || '', area: sl.code ? null : slotAreaKey(sl.title), state: 'cant' };
        grid[ti].slots.push(cell);
        if (!slotCheckable(sl)) {
          if (isConc) {
            concUnchosen++;
            if (!concNote) concNote = sl.note || '';
            if (!concLabel) { var tl = String(sl.title || ''); concLabel = /^Concentration course$/i.test(tl) ? 'Concentration' : tl.replace(/\s*course\s*$/i, ''); }
          } else cant.push(sl);
          return;
        }
        var row;
        if (sl.code) {
          if (isConc) { if (!rows.conc) { var cn = String(sl.note || '').replace(/\s*concentration\s*$/i, ''); rows.conc = { label: (cn ? cn + ' concentration' : 'Concentration'), f: 0, t: 0, n: 0 }; } row = rows.conc; }
          else row = rows.major;
          var cs = window.schSlotCodes(sl.code);
          row.n++;
          var hit = cs.find(function (c) { return have[c] > 0; });
          if (hit) { have[hit]--; row.f++; done.push({ title: sl.title || '', code: hit }); cell.state = 'done'; cell.by = hit; }
          else {
            var th = cs.find(function (c) { return takingM[c] > 0; });
            if (th) { takingM[th]--; row.t++; cell.state = 'taking'; cell.by = th; }
            else { cell.state = 'need'; cell.codes = cs; } if (!th) need.push({ title: sl.title || '', codes: cs, group: isConc ? 'conc' : 'major', ti: ti, year: t.year, term: t.term, units: sl.units });
          }
        } else {
          row = (sl.type === 'ge') ? rows.ge : rows.el;
          row.n++;
          if (uc.done[sl.id]) { row.f++; cell.state = 'done'; }
          else if (uc.taking[sl.id]) { row.t++; cell.state = 'taking'; }
          else { cell.state = 'need'; } if (!uc.done[sl.id] && !uc.taking[sl.id]) needU.push({ title: sl.title || '', type: sl.type, id: sl.id, ti: ti, area: slotAreaKey(sl.title), units: sl.units });
        }
      });
    });
    var list = [rows.major, rows.conc, rows.ge, rows.el].filter(function (r) { return r && r.n > 0; });
    var F = 0, T = 0, N = 0; list.forEach(function (r) { F += r.f; T += r.t; N += r.n; });
    return { major: mm.name, degree: mm.degree, rows: list, F: F, T: T, N: N, cant: cant, concUnchosen: concUnchosen, concNote: concNote,
      concLabel: concLabel || 'Concentration', src: mm.src || '', need: need, needU: needU, grid: grid };
  }

  /* The live crosswalk and prerequisites, paged — the tables are bigger than one PostgREST page. */
  async function loadCatalogTables(sb) {
    async function all(table, cols) {
      var out = [];
      for (var off = 0; off < 40000; off += 1000) {
        var r = await sb.from(table).select(cols).range(off, off + 999);
        if (r.error || !Array.isArray(r.data)) return out.length ? out : null;
        out = out.concat(r.data); if (r.data.length < 1000) break;
      }
      return out;
    }
    var eq = await all('course_equiv', 'legacy_code,current_code');
    if (eq) { eq.forEach(function (r) { var l = normCourse(r.legacy_code), c = normCourse(r.current_code); if (l && c) COURSE_EQUIV_SEED[l] = c; }); buildEquivIndex(); }
    var pr = await all('course_prereqs', 'course_code,prereq_json');
    if (pr) { pr.forEach(function (r) { var c = normCourse(r.course_code), j = r.prereq_json; if (c && j) { try { COURSE_PREREQS_SEED[c] = (typeof j === 'string') ? JSON.parse(j) : j; } catch (e) {} } }); buildPrereqIndex(); }
    return { equiv: !!eq, prereqs: !!pr };
  }

  var MAJOR_NAMES = Object.keys(window.SCHED_MAJORS).map(function (k) { return window.SCHED_MAJORS[k].name; })
    .filter(function (v, i, a) { return a.indexOf(v) === i; }).sort();

  window.TCPL = {
    set: function (o) {
      if (o.student) { student.major = o.student.major || ''; student.conc = o.student.conc || ''; student.standing = o.student.standing || ''; }
      if (o.history) myHistory = o.history.slice();
      if (o.classes) myClasses = o.classes.slice();
      if (o.waived) myWaived = Object.assign({}, o.waived);
      if (o.index) { CLASS_INDEX = o.index; _subjCache = null; }
      if (o.names) Object.keys(o.names).forEach(function (k) { if (!COURSE_NAME[k]) COURSE_NAME[k] = o.names[k]; });
    },
    ledger: ledger, majorFor: majorFor, majors: MAJOR_NAMES, concInfo: concInfo, prereqStatus: prereqStatus,
    coursePrereqs: coursePrereqs, canon: canonCode, completed: completedCodes, geAreaOf: geAreaOf,
    geCourses: GE_COURSES, waiveLabel: waiveReasonLabel, dprLooksLikeOne: dprLooksLikeOne, dprParse: dprParse, pdfItemsToText: pdfItemsToText, fileBytes: fileBytes, abroadMark: ABROAD_MARK, pdfBase: PDFJS_BASE, loadCatalogTables: loadCatalogTables, legal: LEGAL_DOCS
  };
  try { window.dispatchEvent(new Event('tcpl-ready')); } catch (e) {}
})();
