/* Mutation check for check-app: each mutant breaks one promise the app makes; check-app must
   FAIL on every one. A mutant that survives means a test that is not testing anything. */
import fs from 'node:fs'; import path from 'node:path'; import { execFileSync } from 'node:child_process';
const OUT = process.env.SRC_DIR || path.resolve('../out');
const SRC = path.join(OUT, 'app/index.html');
const M = [
  ["profile read asks for concentration", "select('id,display_name,username,avatar_url,major,class_standing').eq('id', me).maybeSingle();", "select('id,display_name,username,avatar_url,major,concentration,class_standing').eq('id', me).maybeSingle();", "profileGrants"],
  ["failed profile read called not set up", "TC.phase = 'profileerr'; render(); return; }", "TC.phase = 'noprofile'; render(); return; }", "profileGrants"],
  ["desktop conc read for any major", "if (d && d.major && d.major === p.major && d.conc", "if (d && d.conc", "profileGrants"],
  ["phone conc read for any account", "if (m && m.u === (TC.user && TC.user.id) && m.major === p.major && m.conc)", "if (m && m.conc)", "profileGrants"],
  ["picked conc not remembered", "if (!e) { TC.profile.concentration = name; concRemember(TC.profile.major, name); }", "if (!e) { TC.profile.concentration = name; }", "profileGrants"],
  ["plan C drawn in My Classes blue", ".plan-C{--pc:#BE185D;", ".plan-C{--pc:#2563EB;", "planColors"],
  ["plans tab loses the plan colour", "    inner = `<div class=\"plancol plan-${S.plan}\">${inner}</div>`;", "", "planColors"],
  ["+ button ignores the plan", "['A', 'B', 'C'].forEach(k => document.body.classList.toggle('plan-' + k, S.plan === k));", "", "planColors"],
  ["unknown friends counted free", "freeN = timed.filter(f => status(f).free === true).length", "freeN = TC.friends.filter(f => status(f).free !== false).length", "me"],
  ["share count invented", "sharedN = (TC.myReviews || []).filter(v => v.share_with_friends).length", "sharedN = 2", "me"],
  ["DPR import from profile without the planner", "try { if (!await TC.loadPlanner()) throw new Error('pdf reader (planner) did not load'); if (TC.myHistory === undefined) await TC.reloadHistory(); UI.dpr", "try { UI.dpr", "dprFromProfile"],
  ["any email allowed", "'Use your school email. It ends in .edu.', ok: false };", "'Use your school email. It ends in .edu.', ok: true };", "signup"],
  ["signup code does not create the account", "const err = await TC.sendCode(email, true); UI.busy.signin = 0;\n    if (err) { si.err = authFriendlyErr(err); return render(); }", "const err = await TC.sendCode(email, false); UI.busy.signin = 0;\n    if (err) { si.err = authFriendlyErr(err); return render(); }", "signup"],
  ["password never set", "const up = await sb.auth.updateUser({ password: pw });", "const up = null;", "signup"],
  ["password sent with the code request", "const r = await sb.auth.signInWithOtp({ email, options: { shouldCreateUser: !!create } });", "const r = await sb.auth.signInWithOtp({ email, options: { shouldCreateUser: !!create, data: { pw: UI.signin.pw } } });", "signup"],
  ["client sends the school", "const row = { id: u.id, edu_email: u.email,", "const row = { school: 'calpoly', id: u.id, edu_email: u.email,", "signup"],
  ["log-in by code makes accounts", "const err = await TC.sendCode(e, false); UI.busy.signin = 0;", "const err = await TC.sendCode(e, true); UI.busy.signin = 0;", "loginNoAccount"],
  ["GA on any host", "if (!declared || loc.host !== declared) return '';", "", "ga"],
  ["GA ignores GPC", "if (nav.globalPrivacyControl === true || nav.globalPrivacyControl === '1') return '';", "", "ga"],
  ["GA page names pass through", "function gaPage(key) { const k = GA_SCREENS[key] ? key : 'app';", "function gaPage(key) { const k = key;", "ga"],
  ["GA page view dropped", "_gaLast = k; gtag('event', 'page_view', gaPage(k));", "_gaLast = k;", "ga"],
  ["waitlist keeps the typed case", "const e = String(email || '').trim().toLowerCase(), school = schoolForEmail(e);", "const e = String(email || '').trim(), school = schoolForEmail(e);", "waitlist"],
  ["missing table shown as joined", "return { err: 'The list isn’t open yet — try again in a day or two.' };", "return { ok: 'joined' };", "waitlist"],
  ["SDSU password sent to auth", "if (eduOk(e) && schoolForEmail(e) !== 'calpoly') { UI.signin.mode = 'waitlist'; UI.signin.err = ''; return render(); }   // SDSU/UCSB: the waitlist", "", "waitlist"],
  ["SDSU session loads Cal Poly app", "if (schoolForEmail(TC.user.email || '') !== 'calpoly') { TC.phase = 'otherschool'; render(); return; }", "", "otherSchoolSession"],
  ["SDSU signs up for an account", "if (eduOk(email) && schoolForEmail(email) !== 'calpoly') { si.mode = 'waitlist';", "if (false) { si.mode = 'waitlist';", "waitlist"],
  ["Plan B back to purple", ".plan-B{--pc:#C2410C;", ".plan-B{--pc:#7C3AED;", "planColors"],
  ["password rule loosened", "return onbEmailHint(si.email, true).ok && String(si.pw || '').length >= 8 && !!si.agree;", "return onbEmailHint(si.email, true).ok && String(si.pw || '').length >= 1 && !!si.agree;", "signup"],
  ["username made optional", "b.disabled = !(f.first.trim() && f.last.trim() && f.okFor && f.okFor === f.username && !UI.busy.ob);", "b.disabled = !(f.first.trim() && f.last.trim() && !UI.busy.ob);", "signup"],
  ["Sean's bird kept", "const onbHawk = size => `<img class=\"onb-hawk\" src=\"${CHAMP}\"", "const onbHawk = size => `<img class=\"onb-hawk\" src=\"data:image/svg+xml,\"", "signedOut"],
  ["confirm without the year", "need = !(pre.standing && pre.major);", "need = !pre.major;", "signup"],
  ["took-before without a term", "const e = await TC.addHistory(code, term, +year, null);", "const e = await TC.addHistory(code, null, null, null);", "signup"],
  ["taking now skips the section", "if (s) {\n    r = await sb.from('my_sections').upsert(", "if (false) {\n    r = await sb.from('my_sections').upsert(", "signup"],
  ["strangers in the payoff", "who: (tookBy[code] || []).filter(id => TC.friends.includes(id)) }))", "who: Object.keys(PEOPLE).filter(id => id !== 'me') }))", "onbFriendsOnly"],
  ["autofilled code lands in one box", "maxlength=\"${i === 0 ? 6 : 1}\"", "maxlength=\"1\"", "signup"],
  ["background render wipes the log-in form", "if (keep && TC.phase !== 'ok' && TC.phase !== 'boot' && TC.phase !== 'offline') return;", "", "signedOut"],
  ["onboarding forgotten on reopen", "if (!m || !TC.user || m.u !== TC.user.id || !m.step) return;", "return;", "signup"],
  ["search rebuilds the screen", "if (r) r.innerHTML = onbManualResults(); }, 150); return; }", "render(true); }, 150); return; }", "signup"],
  ["second code request on Back", "if (si.sentTo === email && Date.now() - (si.sentAt || 0) < 10 * 60 * 1000) {", "if (false) {", "signup"],
  ['description chrome kept', "if (!l) return null; t = t.slice(l.index + l[0].length);", "if (!l) return null;", 'classDetail'],
  ['unknown status counted as full', "return available > 0 ? 'open' : 'unknown';", "return available > 0 ? 'open' : 'full';", 'classDetail'],
  ['orphaned section rows shown', "if (!code || !keep.has(code)) return;", "if (!code) return;", 'friendProfile'],
  ['PolyRatings count dropped', "P.count = p.numEvals || 0;", "P.count = 0;", 'explore'],
  ['would-again counts everyone', "againN.filter(v => v.would_again).length", "againN.length", 'explore'],
  ['review score hardcoded', "course: d.code || null, score: d.stars,", "course: d.code || null, score: 5,", 'rate'],
  ['invented chat reply', "if (!ok) inp.value = v;", "if (!ok) inp.value = v; (TC.rows[id] = TC.rows[id] || []).push({ id: 'fake', sender: 'x', kind: 'text', body: 'lol yes', created_at: new Date().toISOString() });", 'friends'],
  ['plan upsert without conflict key', "sections: list, shared: TC.planShared[slot] !== false }, { onConflict: 'user_id,term,slot' })", "sections: list, shared: TC.planShared[slot] !== false })", 'plans'],
  ['plan removal un-watches everything', "else if (!inP && w && TC.autoWatch[id])", "else if (!inP && w)", 'autowatch'],
  ['Staff treated as a professor', "/^(staff|tba|tbd|to be announced)$/i", "/^(tba)$/i", 'explore'],
  ['fixed prototype clock', "get min() { return slo().min; }", "get min() { return 581; }", 'status'],
  ['Champ ignores open_only', "if (a.open_only && s.status !== 'open') return false;", "", 'champ'],
  ['Champ sends the user id', "JSON.stringify(Object.assign({ q, term: CFG.TERM, who }", "JSON.stringify(Object.assign({ q, term: CFG.TERM, who, user_id: TC.user.id }", 'champ'],
  ['partial seat feed published', "if (!complete || !rows.length) { TC.err.seats = true;", "if (!rows.length) { TC.err.seats = true;", 'seatsPartial'],
  ['second review allowed', "if (iReviewed(pid)) { toast('You’ve already reviewed ' + profName(pid)); return; }", "", 'rateOnce'],
  ['accept by the wrong key', "from('friend_requests').update({ status: 'accepted' }).eq('id', rid)", "from('friend_requests').update({ status: 'accepted' }).eq('from_user', id)", 'requests'],
  ['missing rating filled in', "? PROFS[pk].r : null;", "? PROFS[pk].r : 4.0;", 'noPoly'],
  ['message kind changed', "sender: TC.user.id, kind: 'text', body, payload: null", "sender: TC.user.id, kind: 'msg', body, payload: null", 'friends'],
  ['prototype name on Home', "<div class=\"mk-t\">You might know</div>", "<div class=\"mk-t\">You might know Garrett</div>", 'home'],
  ['me back in the stories', "const stories = TC.friends.map(id =>", "const stories = ['me', ...TC.friends].map(id =>", 'home'],
  ['feed shows only one friend', "TC.friends.length ? TC.friends.map(homeWeekCard).join('')", "TC.friends.length ? TC.friends.slice(0, 1).map(homeWeekCard).join('')", 'home'],
  ['my week put back in the friends feed', "TC.friends.length ? TC.friends.map(homeWeekCard).join('')", "TC.friends.length ? ['me', ...TC.friends].map(homeWeekCard).join('')", 'home'],
  ['shared legend back under Home cards', "  ${week}\n </div>`;", "  ${week}\n  ${shared.size ? '<div class=\"foot\"><span>yellow = shared</span></div>' : ''}\n </div>`;", 'home'],
  ['classes-with-you pill back on friend cards', "    ${isMe ? `<span class=\"pillchip\">${esc(CFG.TERM_LABEL)} · ${nClasses} class${nClasses === 1 ? '' : 'es'}</span>` : ''}", "    <span class=\"pillchip\">${isMe ? `${esc(CFG.TERM_LABEL)} · ${nClasses} class${nClasses === 1 ? '' : 'es'}` : `${shared.size} class${shared.size === 1 ? '' : 'es'} with you`}</span>", 'home'],
  ['block text back to a fixed 10px', "font-size:10px;font-size:clamp(min(10px, (100cqi - 8px) / var(--cw, 2.5)), min((100cqi - 12px) / var(--cw, 2.5), var(--fh, 10px)), 14px);", "font-size:10px;", 'gridTextFill'],
  ['block text ignores the block height', ": (h - 4) / 2.08;", ": h;", 'gridTextFill'],
  ['block text ignores the column width', "min((100cqi - 12px) / var(--cw, 2.5), var(--fh, 10px))", "var(--fh, 10px)", 'gridTextFill'],
  ['block text sized for BUS whatever the code', "const cw = Math.max(textEm(s.code.split(' ')[0]), textEm(s.code.split(' ')[1] || '')).toFixed(2)", "const cw = 2.5", 'gridTextFill'],
  ['beside a tapped day, text ignores the width', "min((100cqi - 8px) / var(--cw, 2.5), var(--fh, 9px))", "var(--fh, 9px)", 'gridTextFill'],
  ['tapped day code stays 11px', ".g-b.wide .g-code{font-size:11px;font-size:clamp(", ".g-b.wide .g-code{font-size:11px;font-size:x(", 'gridTextFill'],
  ['tapped day time ignores the width', "min(var(--fh, 11px) * .86, (100cqi - 24px) / 6.65)", "var(--fh, 11px) * .86", 'gridTextFill'],
  ['tapped day text ignores its height', "wide ? (h - 12 - (faces ? 24 : 0)) / 1.95", "wide ? h", 'gridTextFill'],
  ['columns not size containers', ";container-type:inline-size}", "}", 'gridTextFill'],
  ['untimed sections vanish from Home again', "const untimed = secs.filter(s => !onGrid(s))", "const untimed = secs.filter(s => false)", 'homeNoSetTime'],
  ['weekend-only sections vanish again', "s.e != null && [...s.days].some(d => DAYS.includes(d)), drawn", "s.e != null, drawn", 'homeNoSetTime'],
  ['chips do not say which section', "drawn.has(s.code) && s.sec ? secLabel(s.sec) : ''", "''", 'homeNoSetTime'],
  ['ring on my own chips', "const ring = c => !isMe && mine.has(c) ? ' shared' : '';", "const ring = c => mine.has(c) ? ' shared' : '';", 'homeNoSetTime'],
  ['chips too small to tap', "min-height:42px;padding:8px 11px;", "min-height:30px;padding:6px 11px;", 'homeNoSetTime'],
  ['no-set-time row only when there is no grid', " shared, one: true, fit: 30, H: 300 }) + anyRow;", " shared, one: true, fit: 30, H: 300 });", 'homeNoSetTime'],
  ['online label dropped', "[s.async ? 'Online' : '',", "['',", 'homeNoSetTime'],
  ['section-less chip opens an empty preview', "data-a=\"openClass\" data-x=\"${esc(c)}\"><b>", "data-a=\"secSheet\" data-x=\"${esc(c)}\"><b>", 'homeNoSetTime'],
  ['shared chips lose the ring', "const ring = c => !isMe && mine.has(c) ? ' shared' : '';", "const ring = c => '';", 'homeNoSetTime'],
  ['ring on every chip', "const ring = c => !isMe && mine.has(c) ? ' shared' : '';", "const ring = c => ' shared';", 'homeNoSetTime'],
  ['a No classes band drawn again', "${cols}</div></div>`;", "${cols}<div class=\"g-fold\" style=\"top:40px;height:18px\"><span>No classes</span></div></div></div>`;", 'homeGridFit'],
  ['empty hours folded again', "  /* (no folds: Tate took the \"No classes 2p–6p\" bands back out, 2026-09-30) */\n", "  if (o.fit) { const iv = secs.filter(timed).map(s => [s.s, s.e]).sort((x, y) => x[0] - y[0]); let end = iv.length ? iv[0][1] : S0;\n    for (let i = 1; i < iv.length; i++) { const a = Math.ceil(end / 60) * 60, b = Math.floor(iv[i][0] / 60) * 60; if (b - a >= 120) folds.push([a, b]); end = Math.max(end, iv[i][1]); } }\n", 'homeGridFit'],
  ['story tap does not jump', "el.scrollIntoView({ behavior: calm ?", "0 && el.scrollIntoView({ behavior: calm ?", 'home'],
  ['friend card shows my classes as shared', "const shared = new Set(isMe ? [] : secs.map(s => s.code).filter(c => mine.has(c)));", "const shared = new Set(isMe ? [] : [...mine]);", 'home'],
  ['no friends leaves the feed empty', ": homeWeekCard('me');", ": '';", 'homeNoFriends'],
  ['friend classes error shown as none added', "else if (!isMe && TC.err.friendSecs) week", "else if (0) week", 'homeFriendSecsErr'],
  ['stale friend classes error kept', "TC.friendRows = {}; delete TC.err.friendSecs;", "TC.friendRows = {};", 'homeFriendSecsErr'],
  ['friends load error hidden', "friendsErr ? `<div class=\"card fcard\">", "0 ? `<div class=\"card fcard\">", 'homeFriendsErr'],
  ['signed-out gate removed', "if (TC.phase !== 'ok') {\n    if (TC.phase !== 'boot')", "if (false) {\n    if (TC.phase !== 'boot')", 'signedOut'],
  ['saved classes ignored for me', "const mine = [...new Set((codes.data || []).map(r => canonCode(r.code)).filter(Boolean))];", "const mine = [...new Set((secs.data || []).map(r => canonCode(r.code)).filter(Boolean))];", 'schedule'],
  ['double tap sends twice', "if (UI.busy['f' + id]) return; UI.busy['f' + id] = 1;", "", 'requests'],
  ['word filter skipped', "const bad = wfHit(d.review || '');\n  if (bad) return { err:", "const bad = null;\n  if (bad) return { err:", 'wordFilter'],
  ['failed chat load shown as empty', "if (r.error) { TC.rowsErr[cid] = true;", "if (r.error) { TC.rows[cid] = []; TC.rowsErr[cid] = false;", 'chatFail'],
  ['rate list per class, not per professor', "if (s.prof && !seen[s.prof]) { seen[s.prof] = 1;", "if (s.prof && !seen[s.prof + s.code]) { seen[s.prof + s.code] = 1;", 'rate'],
  ['stat floor removed', "const STAT_MIN = 3;", "const STAT_MIN = 1;", 'prof'],
  ['raw 0–4 PolyRatings score shown', "P.r = +p.numEvals === 0 || !isFinite(+p.overallRating) ? null : Math.round((+p.overallRating / 4 * 5) * 100) / 100;", "P.r = +p.overallRating;", 'prof'],
  ['refusal reason not asked', "const w = await TC.client().rpc('why_cant_i_review');", "const w = { error: null, data: [] };", 'rateRefusedReason'],
  ['JWT expiry not refreshed', "if (r.error && isJwtErr(r.error) && await TC.freshSession(true)) r = await TC.client().from('reviews').insert(row);", "", 'rateJwtRetry'],
  ['unposted review not kept', "function draftLoad(pk) { const x = draftAll()[pk];", "function draftLoad(pk) { return null; const x = draftAll()[pk];", 'rateServerFault'],
  ['waivers ignored by the planner', "classes: [...myCodes()], waived: TC.waived || {},", "classes: [...myCodes()], waived: {},", 'planner'],
  ['edit moves the professor', "const patch = { score: d.stars,", "const patch = { professor_key: 'x|y', score: d.stars,", 'me'],
  ['delete not scoped to the review', "let r = await TC.client().from('reviews').delete().eq('id', id).select('id');", "let r = await TC.client().from('reviews').delete().eq('course', id).select('id');", 'me'],
  ['short password sent', "if (String(pw || '').length < 8) return 'At least 8 characters.';", "", 'settings'],
  ['reserved username allowed', "if (wfReserved(v)) return { ok: false,", "if (false) return { ok: false,", 'editProfile'],
  ['past class stored with a grade', "const row = { user_id: TC.user.id, code, term, year, professor: professor || null };", "const row = { user_id: TC.user.id, code, term, year, professor: professor || null, grade: 'A' };", 'planner'],
  ['oval avatar ring', ".ringav{display:inline-grid;place-items:center;line-height:0}", ".ringav{}", 'ovalRing'],
  ['plan sharing not written', "const r = await TC.client().from('plans').upsert({ user_id: TC.user.id, term: CFG.TERM, slot, sections: list, shared: !!on }", "const r = { error: null }; ({ user_id: TC.user.id, term: CFG.TERM, slot, sections: list, shared: !!on }", 'settings'],
  ['zero-row delete reported as done', "if (!r.error && !(r.data || []).length) r = { error: NOTHING };\n  if (r.error) return dbSay(r.error, 'Couldn’t delete", "if (false) r = { error: NOTHING };\n  if (r.error) return dbSay(r.error, 'Couldn’t delete", 'meNothingChanged'],
  ['ledger counted without its inputs', "if (missing.length) return errCard(", "if (false) return errCard(", 'plannerMissing'],
  ['edit rewrites a blank take-again', "if (d.again === 'yes' || d.again === 'no') patch.would_again = d.again === 'yes';", "patch.would_again = d.again === 'yes'; patch.course = d.code;", 'me'],
  ['review tags dropped', "tags: (d.tags || []).filter(t => RATE_TAGS.includes(t))", "tags: []", 'rateTags'],
  ['struggle chips offered', "const RATE_TAGS = ['Explains concepts clearly',", "const RATE_TAGS = ['Lots of busywork', 'Explains concepts clearly',", 'rateTags'],
  ['already-logged class re-added', "if (x._now && myCodes().has(x.cur)) { x.already = true; x.pick = false; }", "", 'dpr'],
  ['transfer credit not marked', "professor: x._xfer ? TCPL.abroadMark : null", "professor: null", 'dpr'],
  ['friends’ plans read without excluding me', ".eq('term', CFG.TERM).neq('user_id', TC.user.id);", ".eq('term', CFG.TERM);", 'friendPlans'],
  ['grid ignores the ledger (uncoded)', "if (uc.done[sl.id]) { row.f++; cell.state = 'done'; }", "if (uc.done[sl.id]) { row.f++; cell.state = 'need'; }", 'plannerGrid', 'planner'],
  ['a later year opens by default', "const open = UI.plYears[y.year] !== undefined ? UI.plYears[y.year] : y.year === firstOpen;", "const open = UI.plYears[y.year] !== undefined ? UI.plYears[y.year] : true;", 'plannerGrid'],
  ['next term’s classes filed as finished', "else if (x._open && k > cur) { x._now = false; x.skip =", "else if (false) { x._now = false; x.skip =", 'dpr'],
  ['grid counts can’t-check slots as requirements', "judged = slots.length - cant;", "judged = slots.length;", 'plannerGrid'],
  ['profile button back on Explore', "body: `<div class=\"title\">Explore</div>", "body: `<div class=\"title\">Explore</div>${meBtn()}", 'profileHomeOnly'],
  ['home preview: friend card jumps to the class page', "key: id, blockAct: 'secSheet', shared, one: true, fit: 30", "key: id, shared, one: true, fit: 30", 'homeSecPreview'],
  ['home preview: you left out of this section', "const here = (meIn ? ['me'] : []).concat(friendsInSec(id));", "const here = friendsInSec(id);", 'homeSecPreview'],
  ['home preview: other sections dropped', "${secPeopleRow(who.other, 'Other sections')}", "", 'homeSecPreview'],
  ['scroll bars: never hide', "if (y > 60 && dy >= 2) setBars(true);", "", 'scrollHideBars'],
  ['scroll bars: never come back on scroll up', "if (BARS.up >= 12) setBars(false);", "", 'scrollHideBars'],
  ['scroll bars: peek back to half a face', "translate(30px,calc(var(--tb) - 14px - env(safe-area-inset-bottom,0px))) rotate(-12deg)", "translate(42px,calc(var(--tb) - 14px - env(safe-area-inset-bottom,0px))) rotate(-12deg)", 'scrollHideBars'],
  ['scroll bars: new screen keeps them hidden', "BARS.y = sc.scrollTop; BARS.up = 0; setBars(false); }", "BARS.y = sc.scrollTop; BARS.up = 0; }", 'scrollHideBars'],
  ['recent: x removes everything', "recentSave(recentAll().filter(i => !(i.k === k && i.x === x)));", "recentSave([]);", 'recentSearches'],
  ['recent: browsing recorded too', "el.closest('#exlist') && S.q.trim()) recentAdd('c', code);", "el.closest('#exlist')) recentAdd('c', code);", 'recentSearches'],
  ['recent: not per account', "if (m && TC.user && m.u === TC.user.id && Array.isArray(m.items))", "if (m && Array.isArray(m.items))", 'recentSearches'],
  ['recent: oldest first', "recentSave([{ k, x }].concat(recentAll().filter(i => !(i.k === k && i.x === x))));", "recentSave(recentAll().filter(i => !(i.k === k && i.x === x)).concat([{ k, x }]));", 'recentSearches'],
  ['prereq: not fulfilled shown as fulfilled', "unmet: ['Not fulfilled', 'bad', 'prereqGo']", "unmet: ['Fulfilled', 'ok']", 'prereqVerdict'],
  ['prereq: failed history read as empty', "if (TC.err.history || TC.wavErr || TC.err.mine || pl.equiv === false)", "if (TC.wavErr || TC.err.mine || pl.equiv === false)", 'prereqVerdict'],
  ['prereq: failed waivers ignored', "if (TC.err.history || TC.wavErr || TC.err.mine || pl.equiv === false)", "if (TC.err.history || TC.err.mine || pl.equiv === false)", 'prereqVerdict'],
  ['prereq: failed this-term classes ignored', "if (TC.err.history || TC.wavErr || TC.err.mine || pl.equiv === false)", "if (TC.err.history || TC.wavErr || pl.equiv === false)", 'prereqVerdict'],
  ['prereq: failed crosswalk ignored', "if (TC.err.history || TC.wavErr || TC.err.mine || pl.equiv === false)", "if (TC.err.history || TC.wavErr || TC.err.mine)", 'prereqVerdict'],
  ['prereq: failed prereq table read as none', "if (pl.state !== 'ready' || pl.prereqs === false) return { k: 'unknown', text, why: 'tables' };", "", 'prereqVerdict'],
  ['prereq: standing-only called none', "if (!rec || !rec.req || !rec.req.length) return text ? { k: 'unknown', text } :", "if (!rec || !rec.req || !rec.req.length) return false ? { k: 'unknown', text } :", 'prereqVerdict'],
  ['prereq: extra condition hidden behind Fulfilled', "if (st.state === 'met' && PQ_EXTRA.test(text))", "if (false)", 'prereqVerdict'],
  ['prereq: empty record called Not fulfilled', "if (empty && (st.state === 'unmet' || st.state === 'concurrent'))", "if (false)", 'prereqVerdict'],
  ['prereq: Planner card missing', "inner = prereqForCard() + plannerView();", "inner = plannerView();", 'prereqVerdict'],
  ['prereq: finished group listed as needed', "if (d) return `<div class=\"tc-pqgroup\">", "if (false) return `<div class=\"tc-pqgroup\">", 'prereqVerdict'],
  ['prereq: this term’s classes ignored', "const st = TCPL.prereqStatus(code, TCPL.completed(), [], [...myCodes()]);\n  const empty", "const st = TCPL.prereqStatus(code, TCPL.completed(), [], []);\n  const empty", 'prereqVerdict'],
  ['prereq: card lingers after leaving Schedule', "function setTab(t) { if (t !== 'schedule') UI.plFor = null; ", "function setTab(t) { ", 'prereqVerdict'],
  ['now line on a day that is not today', "const now = (wide && d === today && nowMin >= S0 && nowMin <= S1 &&", "const now = (wide && nowMin >= S0 && nowMin <= S1 &&", 'focusDay'],
  ['today starts focused', "S.homeDay = S.schedDay = null; /* nothing is focused until a day is tapped (2026-09-30) */", "S.homeDay = S.schedDay = CLOCK.day;", 'focusDay'],
  ['empty days kept while focused', "const days = focus ? DAYS.filter(d => d === focus || has(d)) : DAYS;", "const days = DAYS;", 'focusDay'],
  ['subject cut off the blocks', "      else inner = `${esc(subj)}<br>${esc(num)}`;   /* always both lines: the subject is never dropped */", "      else inner = esc(num);", 'focusDay'],
  ['same-section faces drawn round', "const same = friendsInSec(s.id), other = friendsIn(s.code).filter(f => !same.includes(f));", "const same = [], other = friendsIn(s.code);", 'focusDay'],
  ['second tap does not clear', "schedDay: d => { S.schedDay = S.schedDay === d ? null : d; render(true); },", "schedDay: d => { S.schedDay = d; render(true); },", 'focusDay'],
  ['room shown on the block', "if (wide) inner = `<span class=\"g-code\">${esc(s.code)}</span>", "if (wide) inner = `<span class=\"g-code\">${esc(s.code)} · Rm 03-0200</span>", 'focusDay'],
  ['home cards back to a fixed height', "key: id, blockAct: 'secSheet', shared, one: true, fit: 30, H: 300 })", "key: id, blockAct: 'secSheet', shared, one: true, H: 300 })", 'homeGridFit'],
  ['fitted grids padded to six hours', "gridSpan(secs, o.fit ? 180 : 360)", "gridSpan(secs, 360)", 'homeGridFit'],
  ['one day for every card', "const k = key || '_';", "const k = '_';", 'homeGridFit'],
  ['day tap loses its card', "${o.key != null ? ` data-y=\"${esc(o.key)}\"` : ''}", "", 'homeGridFit'],
  ['friend page shares the Home card day', "sel: S.homeDays['f:' + id], act: 'homeDay', key: 'f:' + id,", "sel: S.homeDays[id], act: 'homeDay', key: id,", 'homeGridFit'],
  ['long day grows past the old card', "const base = o.fit ? Math.min(o.H || 300, Math.round(vis * pxm + folds.length * FOLD))", "const base = o.fit ? Math.round(vis * pxm + folds.length * FOLD)", 'homeGridFit'],
  ['block hangs past the bottom', "const top = Math.max(0, Math.min(Y(s.s), lim - h));", "const top = Math.max(0, Y(s.s));", 'homeGridFit'],
  ['empty grid for a card with no set times', "  else if (!secs.some(onGrid)) week = anyRow;", "  else if (false) week = anyRow;", 'homeGridFit'],
  ['plan grid shares the friend page day', "sel: S.homeDays['plan:' + id + ':' + k], act: 'homeDay', key: 'plan:' + id + ':' + k,", "sel: S.homeDays['f:' + id], act: 'homeDay', key: 'f:' + id,", 'homeGridFit'],
  ['second tap does not close the card day', "S.homeDays[k] = S.homeDays[k] === d ? null : d;", "S.homeDays[k] = d;", 'homeGridFit'],
  ['section keeps its “-SEM Regular”', "const t = String(v == null ? '' : v).trim().split(/[-\\s]/)[0];", "const t = String(v == null ? '' : v).trim();", 'sectionLabel'],
  ['§ back on the class page', "${s.sec ? esc(secLabel(s.sec)) + ' ' : ''}", "${s.sec ? '§' + esc(secLabel(s.sec)) + ' ' : ''}", 'sectionLabel'],
  ['bare number not called Sec', "return /^\\d/.test(t) ? 'Sec ' + t : t;", "return t;", 'sectionLabel'],
  ['§ back in Champ', "<b>${s.code}${s.sec ? ' ' + esc(secLabel(s.sec)) : ''}</b>", "<b>${s.code}${s.sec ? ' §' + esc(s.sec) : ''}</b>", 'champ'],
  ['+ goes straight to the last plan', 'data-a="addPlanSheet" data-x="${esc(s.id)}"', 'data-a="addSec" data-x="${esc(s.id)}"', 'planPicker'],
  ['preview not see-through', "o.ghost === s.id ? (o.clash ? 'ghost clash' : 'ghost') : ''", "''", 'planPicker'],
  ['clash not shown red', "o.ghost === s.id ? (o.clash ? 'ghost clash' : 'ghost') : ''", "o.ghost === s.id ? 'ghost' : ''", 'planPicker'],
  ['Add goes to the last plan, not the picked one', "if (addSec(sh.id, sh.k)) {", "if (addSec(sh.id)) {", 'planPicker'],
  ['sheet opens on the last plan even when another holds it', "k: hold || (['A', 'B', 'C'].includes(S.plan) ? S.plan : 'A')", "k: (['A', 'B', 'C'].includes(S.plan) ? S.plan : 'A')", 'planPicker'],
  ['open sheet slides in again on every tap', "const again = sh.dataset.open === UI.sheet.type,", "const again = false,", 'planPicker'],
  ['Champ matches any section with the same number', "return m.length === 1 ? m[0] : undefined; }", "return m[0]; }", 'sectionLabel'],
  ['Champ ignores the exact section code', "return r === w || l === w || l === 'SEC ' + w; });", "return false; });", 'sectionLabel'],
  ['onboarding shows the raw section', "<span class=\"s\">${esc(secLabel(sec))}</span>", "<span class=\"s\">Sec ${esc(sec)}</span>", 'sectionLabel'],
  ['clashing section can still be added', "    : clash.length ? `<button class=\"btn\" disabled aria-disabled=\"true\">Clashes — can’t add</button>`\n", "", 'planPicker'],
  ['switch preview keeps the old section', "const keep = others.filter(x => x.code !== s.code);", "const keep = others.filter(x => x.id !== s.id);", 'planPicker'],
  ['+ back in the plan colour', ".secrow .addbtn{background:var(--blue);", ".secrow .addbtnX{background:var(--blue);", 'planColors'],
  ['Rate tab back to orange', "['rate', 'Rate', 'star', '#1D4ED8', '#E3ECFF']", "['rate', 'Rate', 'star', '#D97706', '#FEF1DC']", 'toolbarBlue'],
  ['Friends tab pill back to pink', "['friends', 'Friends', 'users', '#1D4ED8', '#E3ECFF']", "['friends', 'Friends', 'users', '#1D4ED8', '#FCE4F0']", 'toolbarBlue'],
  ['magnifying glass always purple', "style=\"color:var(--${S.exMode === 'profs' ? 'purple' : 'blue'})\"", "style=\"color:var(--purple)\"", 'toolbarBlue'],
  ['magnifying glass always blue', "style=\"color:var(--${S.exMode === 'profs' ? 'purple' : 'blue'})\"", "style=\"color:var(--blue)\"", 'toolbarBlue'],
  ['ratings all one colour', "const rateTone = r => r == null ? null : r * 0.8 >= 3.3 - 1e-9 ?", "const rateTone = r => r == null ? null : true ?", 'ratingColors'],
  ['yellow/red cut-off off by the 4-point scale', "  : r * 0.8 >= 2.5 - 1e-9 ?", "  : r >= 2.5 ?", 'ratingColors'],
  ['star stays amber on the cards', "${starI(13, rateTone(r).star)} ${r.toFixed(1)}", "${starI(13)} ${r.toFixed(1)}", 'ratingColors'],
  ['cards say PolyRatings again', "const line = [p.count ? nRatings(p.count) :", "const line = [p.count ? `${p.count} PolyRatings evaluations` :", 'ratingColors'],
  ['0 evaluations shown as a red 0.0', "P.r = +p.numEvals === 0 || !isFinite(+p.overallRating) ? null :", "P.r =", 'ratingZero'],
  ['No ratings yet beside TermChamp reviews', "(r == null && !st ? 'No ratings yet' : '')", "(r == null ? 'No ratings yet' : '')", 'ratingZero'],
  // no-grow focus + even labels (2026-09-30, focus-no-grow patch)
  ['back-to-back classes squeezed again', "if (dt >= 30 && dt <= 70) pxm = Math.max(pxm, 36 / dt);", "", 'homeGridFit'],
  ['clashing sections blow the card up', "if (dt >= 30 && dt <= 70)", "if (dt > 0 && dt <= 70)", 'homeGridFit'],
  ['minimum height runs into the next class', "nx < Infinity ? Y(nx) - Y(s.s) - 1 : 99", "99", 'homeGridFit'],
  ['tapped day as wide as before', "otherW = nOther ? `max(32px, min(${A} / ${3 * nOther} + 21.333px, (${A} - 110px) / ${nOther}))` : '32px';", "otherW = '32px';", 'homeGridFit'],
  ['tapped day can drop under 110px', "min(${A} / ${3 * nOther} + 21.333px, (${A} - 110px) / ${nOther})", "${A} / ${3 * nOther} + 21.333px", 'focusDayFit'],
  ['focused body grows again', "const H = base;   /* focusing a day never changes the height (Tate, 2026-09-30) */", "const H = focus ? Math.min(900, base * 2) : base;", 'focusDayFit'],
  ['a stray last hour label', "const ms = []; for (let m = S0; m <= S1; m += step) ms.push(m);", "const ms = []; for (let m = S0; m < S1; m += step) ms.push(m); ms.push(S1);", 'focusDayFit'],
  ['labels skip hours on a short card', "const step = STEPS.find(st => span % st === 0 && span / st <= 7) || STEPS.find(st => span / st <= 7) || 240;", "const step = span > 480 ? 180 : 120;", 'homeGridFit'],
  ['short wide blocks keep the three-row layout', "const tight = wide && h < (faces ? 56 : 36);   /* no room for three rows */", "const tight = false;", 'focusDayFit'],
  ['wide blocks back to a 34px minimum', "const h = Math.max((s.e - s.s) * k, Math.min(o.fit ? 26 : (o.one ? 30 : 24), nx < Infinity ? Y(nx) - Y(s.s) - 1 : 99));\n      const tight", "const h = Math.max((s.e - s.s) * k, wide ? 34 : Math.min(o.fit ? 26 : (o.one ? 30 : 24), nx < Infinity ? Y(nx) - Y(s.s) - 1 : 99));\n      const tight", 'focusDayFit'],
  ['+N dropped from a tight block', ".g-b.wide.tight .g-time{font-size:9px;grid-column:1;grid-row:2}", ".g-b.wide.tight .g-time{font-size:9px;grid-column:1;grid-row:2}.g-b.wide.tight .g-more{display:none}", 'focusDayFit'],
  ['+N drawn ahead of the faces it counts', ".g-b.wide.tight .g-code{font-size:10px;grid-column:1;grid-row:1}", ".g-b.wide.tight .g-code{font-size:10px;grid-column:1;grid-row:1}.g-b.wide.tight .g-more{order:-1}", 'focusDayFit'],
  ['friend count left off the block title', "(nf ? ` · ${nf} friend${nf === 1 ? '' : 's'} in this class` : '')", "''", 'focusDayFit'],
  ['tight text centred', "align-items:center;justify-items:start;column-gap:5px", "align-items:center;column-gap:5px", 'focusDayFit'],
  ['tight faces clipped instead of wrapped', "display:flex;flex-wrap:wrap;gap:20px 2px;justify-content:flex-end;align-content:flex-start;max-height:23px;overflow:hidden}", "display:flex;flex-wrap:nowrap;gap:2px;justify-content:flex-end;align-content:flex-start;max-height:23px;overflow:hidden}", 'focusDayFit'],
  // Home width (2026-09-30, home-width patch)
  ['Home cards back to 16px from the edge', ".homepg .hfeed .fcard{margin:0 var(--hg)}", ".homepg .hfeed .fcard{margin:0 16px}", 'homeWidth'],
  ['header and stories left at 16px', ".homepg .homehdr,.homepg .stories{padding-left:var(--hg);padding-right:var(--hg)}", ".homepg .homehdr{padding-left:var(--hg);padding-right:var(--hg)}", 'homeWidth'],
  ['Home grid back to 14px inside the card', ".homepg .fcard .grid{padding:4px 8px 0;--glab:26px;--ggap:5px}", ".homepg .fcard .grid{padding:4px 14px 0;--glab:26px;--ggap:5px}", 'homeWidth'],
  ['hour column ignores the Home width', ".g-head,.g-body{display:grid;grid-template-columns:var(--glab,30px) repeat(5,1fr);gap:var(--ggap,6px)}", ".g-head,.g-body{display:grid;grid-template-columns:30px repeat(5,1fr);gap:6px}", 'homeWidth'],
  ['Home width leaks into Schedule', ".homepg{--hg:12px}", ".homepg{--hg:12px}\n.grid{padding:4px 8px 0;--glab:26px;--ggap:5px}", 'homeWidth'],
  ['tapped Home day back to a 30px hour column', "  const tmpl = focus ? `grid-template-columns:var(--glab,30px) ${days.map(", "  const tmpl = focus ? `grid-template-columns:30px ${days.map(", 'homeWidth'],
  ['Where your friends are left at 16px', '<div class="card where" style="margin:0 var(--hg,16px)">', '<div class="card where" style="margin:0 16px">', 'homeWidth'],
  ['axis fixed at 6a–10p again', "  if (!t.length) return [480, 1080];\n  let a = Math.floor(Math.min(...t.map(s => s.s)) / 60) * 60, b = Math.ceil(Math.max(...t.map(s => s.e)) / 60) * 60;", "  if (!t.length) return [480, 1080];\n  let a = 360, b = 1320;", 'focusDayFit'],
  ['friend plans claimed empty before loading', "if (!TC.friendPlans || TC.err.friendPlans) return '';", "if (TC.err.friendPlans) return ''; TC.friendPlans = TC.friendPlans || {};", 'friendPlansLoading'],
];
const html = fs.readFileSync(SRC, 'utf8');
const pl = fs.readFileSync(path.join(OUT, 'app/planner.js'), 'utf8');
const tmp = fs.mkdtempSync('/tmp/claude-0/mut-'); fs.mkdirSync(path.join(tmp, 'app'));
let caught = 0, survived = [];
const ONLY = process.env.MUT_ONLY ? process.env.MUT_ONLY.split('|') : null;
for (const [name, a, b, test, target] of M) {
  if (ONLY && !ONLY.includes(name)) continue;
  const src = target === 'planner' ? pl : html;
  const n = src.split(a).length - 1;
  if (n !== 1) { console.log('  BAD MUTANT (found ' + n + '×):', name); survived.push(name + ' (bad)'); continue; }
  fs.writeFileSync(path.join(tmp, 'app', 'index.html'), target === 'planner' ? html : html.replace(a, b));
  fs.writeFileSync(path.join(tmp, 'app', 'planner.js'), target === 'planner' ? pl.replace(a, b) : pl);
  let failed = false;
  try { execFileSync('node', ['check-app.mjs', '--quiet', '--only', test], { env: { ...process.env, APP_DIR: tmp }, stdio: 'pipe', timeout: 300000 }); }
  catch (e) { failed = true; }
  if (failed) { caught++; console.log('  caught  ', name); } else { survived.push(name); console.log('  SURVIVED', name); }
}
console.log(`\nmutations: ${caught}/${M.length} caught`);
if (survived.length) { console.log('survived:', survived.join(' | ')); process.exit(1); }
